export const BUY_POKEMON = 'BUY_POKEMON';
export const SELL_POKEMON = 'SELL_POKEMON';
export const LOAD_POKEMON = 'ASYNC_LOAD_POKEMON';
export const LOAD_POKEMON_SUCCESS = 'LOAD_POKEMON_SUCCESS';
export const LOAD_POKEMON_ERR = 'LOAD_POKEMON_ERR';
export const CHANGE_VALUES_POKEMON = 'CHANGE_VALUES_POKEMON';