export const ADD_POKEMON_TO_POKEDEX = 'ADD_POKEMON_TO_POKEDEX';
export const REMOVE_POKEMON_TO_POKEDEX = 'REMOVE_POKEMON_TO_POKEDEX';
export const LOAD_POKEMON_INFO = 'ASYNC_LOAD_POKEMON';
export const LOAD_POKEMON_INFO_SUCCESS = 'LOAD_POKEMON_SUCCESS';
export const LOAD_ALL_POKEMON = 'ASYNC_LOAD_ALL_POKEMON';
export const LOAD_ALL_POKEMON_SUCCESS = 'LOAD_ALL_POKEMON_SUCCESS';